services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=q1w2e3r4
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_=